### ISSUE TITLE
depends on cachedflickvideoplayer from git which requires SDK version >=2.7.0 <2.11.0, version solving failed.

### ISSUE THREAD

**Issue by aliaktas-tr** [elgsylvain85/cachedflickvideoplayer#1]
depends on cachedflickvideoplayer from git which requires SDK version >=2.7.0 <2.11.0, version solving failed.

**Comment by elgsylvain85** [comment]
I don't support anymore this, please follow the logic to update dependencies. Reminder that this project is fusion of "cachedflick" and "videoplayer" plugins.
